[phases.setup]
nixPkgs = ["nodejs_20", "nodePackages.npm"]

[phases.install]
cmds = ["cd client && npm install && npm run build", "cd server && npm install"]

[phases.build]
cmds = ["echo 'Build complete'"]

[start]
cmd = "cd server && npm start" 